# vim: set ft=yaml ts=2 expandtab:
---

- name: Distribution dependent variables
  include_vars: "{{ ansible_distribution }}.yml"
    
- name: assertions
  assert:
    that:
      - ansible_distribution in [ "CentOS" ]
      - ansible_distribution_version is version("8.0", "<")

- name: install ntpd
  package:
    name:
      - ntp
      - ntpdate
    state: present

- block:

    - name: ntp.conf
      when: ntp_conf_file is not defined
      template:
        src: ntp.conf.j2
        dest: /etc/ntp.conf
        backup: true
      notify: reload ntpd
    
    - name: ntp.conf
      when: ntp_conf_file is defined
      template:
        src: "{{ playbook_dir }}/{{ ntp_conf_file }}"
        dest: /etc/ntp.conf
        backup: true
      notify: reload ntpd

- name: start ntpd
  service:
    name: ntpd
    state: started
    enabled: true
  register: _ntp_started

...
