---

- name: Distribution dependent variables
  include_vars: "{{ ansible_distribution }}.yml"
    
- name: install ntpd
  package:
    name: ntp
    state: present

- name: ntp.conf
  template:
    src: "{{ item }}"
    dest: /etc/ntp.conf
    backup: true
  with_items:
#    - "{{ playbook_dir }}/templates/{{ ntp.cfg }}"
    - ntp.conf.j2
  notify: reload ntpd

- name: start ntpd
  service:
    name: ntpd
    state: started
    enabled: yes
